permalink: /:year/:month/:day/:title.html
markdown: redcarpet
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 马超
  email: drizzt@aliyun.com
  link: https://lydon18.github.io/
  weibo: http://weibo.com/drizztblog
  github: http://github.com/DrizztM

# 站点信息
title: 马超的博客 
description: 马超的博客
url: http://blog.drizzt.cn
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar:  /assets/img/logo.png
favicon:  /assets/img/logo.png

# disqus 设置
disqus:
  shortname: drizztblog